function java(){
	document.getElementById("java1").style.display="block",
	document.getElementById("dotnet1").style.display="none";
	document.getElementById("python1").style.display="none";
	document.getElementById("ruby1").style.display="none";
	document.getElementById("node1").style.display="none";
	document.getElementById("maven1").style.display="none";
	document.getElementById("gradle1").style.display="none";
	document.getElementById("msbuild1").style.display="none";
	document.getElementById("pybuilder1").style.display="none";
	document.getElementById("rake1").style.display="none";
	document.getElementById("grunt1").style.display="none";
}
function dotnet(){
	document.getElementById("java1").style.display="none",
	document.getElementById("dotnet1").style.display="block";
	document.getElementById("python1").style.display="none";
	document.getElementById("ruby1").style.display="none";
	document.getElementById("node1").style.display="none";
	document.getElementById("maven1").style.display="none";
	document.getElementById("gradle1").style.display="none";
	document.getElementById("msbuild1").style.display="none";
	document.getElementById("pybuilder1").style.display="none";
	document.getElementById("rake1").style.display="none";
	document.getElementById("grunt1").style.display="none";
}
function python(){
	document.getElementById("java1").style.display="none",
	document.getElementById("dotnet1").style.display="none";
	document.getElementById("python1").style.display="block";
	document.getElementById("ruby1").style.display="none";
	document.getElementById("node1").style.display="none";
	document.getElementById("maven1").style.display="none";
	document.getElementById("gradle1").style.display="none";
	document.getElementById("msbuild1").style.display="none";
	document.getElementById("pybuilder1").style.display="none";
	document.getElementById("rake1").style.display="none";
	document.getElementById("grunt1").style.display="none";
}
function ruby(){
	document.getElementById("java1").style.display="none",
	document.getElementById("dotnet1").style.display="none";
	document.getElementById("python1").style.display="none";
	document.getElementById("ruby1").style.display="block";
	document.getElementById("node1").style.display="none";
	document.getElementById("maven1").style.display="none";
	document.getElementById("gradle1").style.display="none";
	document.getElementById("msbuild1").style.display="none";
	document.getElementById("pybuilder1").style.display="none";
	document.getElementById("rake1").style.display="none";
	document.getElementById("grunt1").style.display="none";
}
function node(){
	document.getElementById("java1").style.display="none",
	document.getElementById("dotnet1").style.display="none";
	document.getElementById("python1").style.display="none";
	document.getElementById("ruby1").style.display="none";
	document.getElementById("node1").style.display="block";
	document.getElementById("maven1").style.display="none";
	document.getElementById("gradle1").style.display="none";
	document.getElementById("msbuild1").style.display="none";
	document.getElementById("pybuilder1").style.display="none";
	document.getElementById("rake1").style.display="none";
	document.getElementById("grunt1").style.display="none";
}
function maven(){
	document.getElementById("java1").style.display="none",
	document.getElementById("dotnet1").style.display="none";
	document.getElementById("python1").style.display="none";
	document.getElementById("ruby1").style.display="none";
	document.getElementById("node1").style.display="block";
	document.getElementById("maven1").style.display="none";
	document.getElementById("gradle1").style.display="none";
	document.getElementById("msbuild1").style.display="none";
	document.getElementById("pybuilder1").style.display="none";
	document.getElementById("rake1").style.display="none";
	document.getElementById("grunt1").style.display="none";
}
function gradle(){
	document.getElementById("java1").style.display="none",
	document.getElementById("dotnet1").style.display="none";
	document.getElementById("python1").style.display="none";
	document.getElementById("ruby1").style.display="none";
	document.getElementById("node1").style.display="block";
	document.getElementById("maven1").style.display="none";
	document.getElementById("gradle1").style.display="none";
	document.getElementById("msbuild1").style.display="none";
	document.getElementById("pybuilder1").style.display="none";
	document.getElementById("rake1").style.display="none";
	document.getElementById("grunt1").style.display="none";
}